# .github/workflows/lint-and-test.yml

name: Lint and Test

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Node.js 21.x
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install


      # 4) Run tests
      - name: Run tests
        run: npx cypress run

