name: Lint and Test

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      # Install dependencies (including start-server-and-test and Cypress)
      - name: Install dependencies
        run: npm install

      # Start the server and run Cypress in one step
      - name: Run server & Cypress tests
        run: npm run test:ci
